language: python
python:
  - "3.6"
services:
  - postgresql

install:
  - cd API_Extended_Document
  - export PYTHONPATH=$PYTHONPATH:.
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database extendeddoc;' -U postgres
  - psql -c '\l' -U postgres

script:
  - pwd
  - pytest -s
